### ISSUE TITLE
Water behind Translucent Fertilizer does not render

### ISSUE THREAD

**Issue by Bluey16** [bernie-g/geckolib-examples#5]
Version: ML 1.21.3

Water and most likely all other Fluids do not render behind the Fertilizer. I had the same issue on another Mod I am working on and thought I could look at the examples to see what I am doing wrong, but it seems to be a general problem with blocks which contain any translucency.
Could be an issue with MC generally, but if GeckoLib offers any fixes (somehow) against it, would be nice to have it in the examples :)
![2024-11-30_11 58 42](https://github.com/user-attachments/assets/b36f0b4e-33b1-4aa3-81e7-9f413cd0a07b)

**Comment by Tslat** [comment]
It's an issue with _computers_ generally

This is an unsolved issue called translucency sorting, and you won't find a fix in Geckolib (or anywhere else) lol
